name: fitgenie
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  google_generative_ai: ^0.4.7
  flutter_dotenv: ^6.0.0
  connectivity_plus: ^7.0.0
  go_router: ^17.0.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_animate: ^4.5.2
  shimmer: ^3.0.0
  firebase_app_check: ^0.4.1+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.0
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
